Rewriting testing history

diff --git a/build/node/steps/script-in-package.yml b/build/node/steps/script-in-package.yml
--- a/build/node/steps/script-in-package.yml
+++ b/build/node/steps/script-in-package.yml
@@ -1,8 +1,31 @@
 parameters:
-  build_tool: ${{ coalesce($(BUILD_TOOL), 'yarn') }}
+  # overrides
+  debug: $(debug)
+  build_tool: $(build_tool)
+
+  # step specifics
   script_name: ''
   extra_arguments: ''
 
 steps:
-  - script: ${{ parameters.build_tool }} run ${{ script_name }} ${{ extra_arguments }}
+  - script: |
+      # debugger
+      if [ "${{ parameters.debug }}" == "true" ]; then
+        echo "##[section] Partial: Debug"
+        echo "##[debug] Using ${{ parameters.build_tool }} as build tool";
+        echo "##[debug] Passing ${{ coalesce(parameters.script_name, '-empty-') }} as script name";
+        echo "##[debug] Passing ${{ coalesce(parameters.extra_arguments, '-empty-') }} as extra arguments";
+        echo "##[section] Partial: Debug"
+      fi
+
+      echo "##[section] Partial: Validation"
+      if [ -z "${{ parameters.script_name }}" ]; then
+        echo "##[error] A script name is required"
+        exit 1
+      fi
+      echo "##[section] Partial: Validation"
+
+      echo "##[section] Partial: Step"
+      ${{ parameters.build_tool }} run ${{ script_name }} ${{ extra_arguments }}
+      echo "##[section] Partial: Step"
     displayName: 'Execute ${{ script_name }} in package.json'
diff --git a/build/node/steps/setup/install-dependencies.yml b/build/node/steps/setup/install-dependencies.yml
--- a/build/node/steps/setup/install-dependencies.yml
+++ b/build/node/steps/setup/install-dependencies.yml
@@ -1,6 +1,27 @@
 parameters:
-  extra_arguments: ''
+  # overrides
+  debug: $(debug)
+  build_tool: "$(build_tool)"
+
+  # step specifics
+  extra_arguments: ""
 
 steps:
-  - script: $(build_tool) install ${{ parameters.extra_arguments }}
-    displayName: '[ Setup ] - Getting dependencies from registry'
+  - script: |
+      if [ -z "${{ parameters.build_tool }}" ]; then
+        echo "##[error] A build tool is required"
+        exit 1
+      fi
+    displayName: "Getting dependencies from registry - Validation"
+  - script: |
+      if [ "${{ parameters.debug }}" == "true" ]; then
+        echo "##[section] Debugger >>"
+        echo "##[debug] Using ${{ parameters.build_tool }} as build tool";
+        echo "##[debug] Passing ${{ coalesce(parameters.extra_arguments, '-empty-') }} as extra arguments";
+        echo "##[section] << Debugger"
+      fi
+
+      echo "##[section] Body >>"
+      ${{ parameters.build_tool }} install ${{ parameters.extra_arguments }}
+      echo "##[section] << Body"
+    displayName: "Getting dependencies from registry"
diff --git a/build/node/steps/setup/lerna-bootstrap.yml b/build/node/steps/setup/lerna-bootstrap.yml
--- a/build/node/steps/setup/lerna-bootstrap.yml
+++ b/build/node/steps/setup/lerna-bootstrap.yml
@@ -1,10 +1,32 @@
 parameters:
-  extra_arguments: ''
+  # overrides
+  debug: $(debug)
+  build_tool: "$(build_tool)"
+
+  # step specifics
   use_yarn_workspaces: false
+  extra_arguments: ""
 
 steps:
-  - script: yarn config set workspaces-experimental true
-    condition: ${{ and( eq(build_tool, 'yarn'), parameters.use_yarn_workspaces ) }}
-    displayName: '[ Setup ] - Setting up yarn workspaces'
-  - script: lerna bootstrap ${{ parameters.extra_arguments }}
-    displayName: '[ Setup ] - Bootstrapping packages with lerna'
+  - script: |
+      if [ -z "${{ parameters.build_tool }}" ]; then
+        echo "##[error] A build tool is required"
+        exit 1
+      fi
+    displayName: "Bootstrapping packages with lerna - Validation"
+  - script: |
+      if [ "${{ parameters.debug }}" == "true" ]; then
+        echo "##[section] Debugger >>"
+        echo "##[debug] Passing ${{ parameters.use_yarn_workspaces }} as flag for yarn workspaces";
+        echo "##[debug] Passing ${{ coalesce(parameters.extra_arguments, '-empty-') }} as extra arguments";
+        echo "##[section] << Debugger"
+      fi
+
+      echo "##[section] Body >>"
+      if [ "${{ parameters.use_yarn_workspaces }}" == "true" && "${{ parameters.build_tool }}" == "yarn" ]; then
+        yarn config set workspaces-experimental true
+      fi
+
+      npx lerna bootstrap ${{ parameters.extra_arguments }}
+      echo "##[section] << Body"
+    displayName: "Bootstrapping packages with lerna"
