feat(job): Updates to variable determination

diff --git a/build/node/job.yml b/build/node/job.yml
--- a/build/node/job.yml
+++ b/build/node/job.yml
@@ -1,9 +1,9 @@
 parameters:
-  # pipeline flow control
+  # pipeline scope
   debug: $(pipeline.debug)
   build_tool: "$(pipeline.build_tool)"
 
-  # job specifics
+  # job scope
   name: "windows"
   vmImage: "vs2017-win2016"
   matrix:
@@ -21,10 +21,21 @@ jobs:
         ${{ parameters.matrix }}
 
     variables:
-      debug: ${{ parameters.debug }}
+      debug: ${{ or(parameters.debug, variables.system.debug) }}
       build_tool: ${{ parameters.build_tool }}
 
     steps:
+      - script: |
+          if [ -z "${{ parameters.build_tool }}" ]; then
+            echo "##[error] A build tool is required"
+            exit 1
+          fi
+
+          if [ ${#steps[@]} -eq 0 ]; then
+            echo "##[error] At least one step is required"
+          fi
+        displayName: "Node Installation - Validation"
+
       - task: NodeTool@0
         inputs:
           versionSpec: $(node_version)
diff --git a/build/node/steps/validation/lint.yml b/build/node/steps/validation/lint.yml
--- a/build/node/steps/validation/lint.yml
+++ b/build/node/steps/validation/lint.yml
@@ -8,7 +8,7 @@ parameters:
   glob: "."
   extra_arguments: ""
 
-  # expensions
+  # extensions
   validation: []
 
 steps:
@@ -17,19 +17,25 @@ steps:
         echo "##[error] A linter tool is required"
         exit 1
       fi
+
+      if [ -z "${{ parameters.glob }}" ]; then
+        echo "##[error] A glob is required"
+        exit 1
+      fi
     displayName: "${{ parameters.displayName }} - General validation"
+
   - ${{ parameters.validation }}
+
   - script: |
       if [ "${{ parameters.debug }}" == "true" ]; then
-        echo "##[section] Partial: Debug"
+        echo "##[section] Debug >>"
         echo "##[debug] Using ${{ parameters.linter }} as linter tool";
         echo "##[debug] Using ${{ parameters.glob }} as file selector"
-        echo "##[debug] Using ${{ parameters.extensions }} as filter"
         echo "##[debug] Passing ${{ coalesce(parameters.extra_arguments, '-empty-') }} as extra arguments";
-        echo "##[section] Partial: Debug"
+        echo "##[section] << Debug"
       fi
 
-      echo "##[section] Partial: Step"
+      echo "##[section] Body >>"
       ${{ parameters.linter }} ${{ parameters.glob }} ${{ parameters.extra_arguments }}
-      echo "##[section] Partial: Step"
+      echo "##[section] << Body"
     displayName: ${{ parameters.displayName }}
